### ISSUE TITLE
VirtualBox Guest Additions Not Installed

### ISSUE THREAD

**Issue by MattHodge** [mwrock/packer-templates#13]
Not sure if this is a problem with VBox 5+ or something I am doing.. but there are no virtualbox guest additions installed with v0.4.0.

**Comment by mwrock** [comment]
thats right. This was also mentioned in #11. The main reason for doing this is there was that I was running into issues where things would intermittently break when uploading the guest additions. I did not really need them for my purposes at the time but it would be good to include them.

**Comment by MattHodge** [comment]
https://github.com/dotless-de/vagrant-vbguest may be a soltuion but seems broken with Windows currently. 

Can use the following in `config.vm.provision "shell"`:

```powershell
if (-not(Test-Path -Path 'C:\Program Files\Oracle\VirtualBox Guest Additions'))
{
    $url = 'http://download.virtualbox.org/virtualbox/5.0.4/VBoxGuestAdditions_5.0.4.iso'
    $downloadLocation = "$($env:TEMP)\VBoxGuestAdditions.iso"

    (New-Object System.Net.WebClient).DownloadFile($url, $downloadLocation)

    $iso = Mount-DiskImage -ImagePath $downloadLocation -PassThru
    $mountLocation = "$((Get-Volume -DiskImage $iso).DriveLetter):\"

    Start-Process -FilePath "$($mountLocation)\cert\VBoxCertUtil.exe" -ArgumentList "add-trusted-publisher $($mountLocation)\cert\oracle-vbox.cer" -Wait -NoNewWindow

    Start-Process -FilePath "$($mountLocation)\VBoxWindowsAdditions.exe" -ArgumentList "/S" -Wait -NoNewWindow

    Dismount-DiskImage -ImagePath $downloadLocation
}
```

Problem is you need to reboot the box for it to pick up the tools.. :(
