### ISSUE TITLE
vboxmanage convert to VHD

### ISSUE THREAD

**Issue by Plork** [mwrock/packer-templates#30]
Got some weird error when running the psake build. When it tries to convert the disk to a vhd it does complete only psake thinks the returned progress is an exception.

Error: 21-12-2015 09:26:25: 
At D:\TFS\Work\Development\Packer-Templates\psakeBuild.ps1:32 char:3 +   ."$env:programfiles\oracle\VirtualBox\VBoxManage.exe" -q clonemediu ... +   ~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

I see the disk in the output directory. When I run the command via a dos prompt it all runs fine. Tried to debug the powershell but I am kinda new with Psake.

Seen this before? dunno if it's Psake or just powershell jet. (WMF 5 on Windows 10)

**Comment by mwrock** [comment]
Hm. No I haven't seen this before.

**Comment by Plork** [comment]
Oke turns out this is only an issue when you run the scripts via the ISE. powershell.exe does't have this problem.

weird that the editor handles output differently.
