### ISSUE TITLE
Boxstarter 2.6.25 requires chocolatey '-y' to proceed

### ISSUE THREAD

**Issue by jwatson3d** [mwrock/packer-templates#31]
I think the logic inside the Boxstarter bootstrapper where it checks for a -v to also decide if -y is needed isn't working. Attached is a screenshot of the bootstrapper hanging, I needed to capture focus then type a '1' and press Enter to continue...
![2015-12-30_13-34-40](https://cloud.githubusercontent.com/assets/1030403/12055334/397c765c-aefa-11e5-85a6-babaeb4275c1.png)

**Comment by mwrock** [comment]
Ah. Yes does look like it is broken on win 7/2008r2. Just pushed a fix. Thanks!!
