### ISSUE TITLE
Building server 2012, I get a "Language to install" dialog

### ISSUE THREAD

**Issue by pfmoore** [mwrock/packer-templates#47]
When I run the ```vbox2012-r2.json``` template, Windows Setup pauses with a "Language to install" dialog. Is this to be expected?

I have made some changes to the template to match my configuration - I switched to a local ISO, and added my license key to the ```autounattend.xml```. I also changed the locale to ```en-GB``` and the timezone to GMT Standard. Could these changes be the issue (I thought autounattend.xml was used later in the build, so would not affect this part of the build, but I'm not very familiar with Windows provisioning, so I could easily be mistaken)?

Alternatively, is there a better way to switch the language/timezone and use an activation key, that I should be using rather than hacking the install scripts?

**Comment by mwrock** [comment]
I've never encountered this before, but I always use the eval ISO and stick with the default locale/timezone. I'd be fairly certain this is either due to your specific ISO or the locale/timezone settings. I'm sure the product key is unrelated.

What I'd do is revert your locale/timezone changes and just see if that fixes it to isolate the settings from the ISO. I'm not sure what the fix would be other than it is somewhere in the autounattend.xml.

**Comment by pfmoore** [comment]
OK, thanks. I'll try that (so I just have my own ISO, but everything else unchanged) and see if that fixes it. If it does, I'll see if I can work out another way of making the changes I want post-install.

BTW, if I want to disable the windows update step (so I can run some tests in a reasonable length of time!) can I do that just by commenting out the ```Install-WindowsUpdate -AcceptEula``` line in ```scripts/package.ps1```?

**Comment by mwrock** [comment]
Yeah that should cut out about 6 hours :)

**Comment by pfmoore** [comment]
Sigh. Looks like it was from putting the language in autounattend.xml. Off to do some research on autounattend then...

Thanks for your help, and apologies for not researching more fully before raising the issue here.

**Comment by mwrock** [comment]
no worries. The autounattend can be pretty cryptic indeed.

**Comment by pfmoore** [comment]
Looks like Windows these days comes without language packs included by default. If you change language manually, I guess it installs what it needs.

For information, should anyone else find this thread, the following powershell code can change the language:
```
Set-WinSystemLocale -SystemLocale en-GB
Set-WinSystemLocale en-GB 
Set-Culture en-GB
Set-WinUserLanguageList en-GB -force
Set-WinHomeLocation 242 # UK, US is 244
```

There's more (you need to download and install the language pack, and you need to somehow copy the current user values to the welcome screen and new user accounts (there's a GUI for that in the control panel, but I don't know what the powershell commands would be, yet), but the basic answer is that you *can* do it.

Add to that the fact that with DISM it appears you can activate an evaluation version with a full product key, and it looks like I can do all I need in a vagrant provisioning script from your base box (and then repackage the box for further customisation, if needed). Which is really cool.
