### ISSUE TITLE
Minor Issue

### ISSUE THREAD

**Issue by glennsarti** [mwrock/packer-templates#64]
In the release notes for Windows Server 2012R2 (https://atlas.hashicorp.com/mwrock/boxes/Windows2012R2/versions/0.6.0) you use US date format (` ... 12/17/2016 ...`.  This is such a small issue, but it makes it harder to read for those not in the US.  Would prefer either written in full (16th Dec 2016) or a more sortable format (2016-12-17).

PS I feel petty raising such a small issue :-(

**Comment by mwrock** [comment]
That is super easy to fix so totally worth it and done. Thanks!
