### ISSUE TITLE
oracle.cer  in git repo is expired

### ISSUE THREAD

**Issue by andybrucenet** [mwrock/packer-templates#69]
When installing using `packer build -force -only virtualbox-iso ./vbox-2016.json` there is a failure installing Windows Additions for Virtual Box:
`    virtualbox-iso: ================================================================================
    virtualbox-iso: Error executing action `install` on resource 'windows_package[virtual box guest additions]'
    virtualbox-iso: ================================================================================
    virtualbox-iso:
    virtualbox-iso: Mixlib::ShellOut::ShellCommandFailed
    virtualbox-iso: ------------------------------------
    virtualbox-iso: Expected process to exit with [0], but received '1'
    virtualbox-iso: ---- Begin output of start "" /wait "e:\vboxwindowsadditions.exe"   /S & exit %%%%ERRORLEVEL%%%% ----
    virtualbox-iso: STDOUT:
    virtualbox-iso: STDERR:
    virtualbox-iso: ---- End output of start "" /wait "e:\vboxwindowsadditions.exe"   /S & exit %%%%ERRORLEVEL%%%% ----
    virtualbox-iso: Ran start "" /wait "e:\vboxwindowsadditions.exe"   /S & exit %%%%ERRORLEVEL%%%% returned 1
    virtualbox-iso:
    virtualbox-iso: Resource Declaration:
    virtualbox-iso: ---------------------
    virtualbox-iso: # In c:/windows/temp/packer-chef-solo/local-mode-cache/cache/cookbooks/packer-templates/recipes/vbox_guest_additions.rb
    virtualbox-iso:
    virtualbox-iso: 13: package "virtual box guest additions" do
    virtualbox-iso: 14:   source "e:/VBoxWindowsAdditions.exe"
    virtualbox-iso: 15:   installer_type :custom
    virtualbox-iso: 16:   options "/S"
    virtualbox-iso: 17: end
    virtualbox-iso:
    virtualbox-iso: Compiled Resource:
    virtualbox-iso: ------------------
    virtualbox-iso: # Declared in c:/windows/temp/packer-chef-solo/local-mode-cache/cache/cookbooks/packer-templates/recipes/vbox_guest_additions.rb:13:in `from_file'`

Problem is that `oracle.cer` included with git repo expired 12/22/2016.

Solved by patching `cookbooks/packer-templates/recipes/vbox_guest_additions.rb`:
`dsc_resource "Install Oracle Cert" do
  resource :xCertificateImport
  property :Thumbprint, "7e92b66be51b79d8ce3ff25c15c2df6ab8c7f2f2"
  property :Store, "TrustedPublisher"
  property :Location, "LocalMachine"
  property :Path, "E:/cert/vbox-sha1.cer"
end`

Note that I leverage the certificate automatically included by VirtualBox on the mounted E: drive for the running guest. Oracle actually provides three versions of certificates - SHA1, SHA256 and a SHA256-r3 but the SHA1 is the one that seems to work.

**Comment by mwrock** [comment]
Yes there is a PR #65 that addresses this for 2012r2 and will need to follow the same pattern for 2016.

**Comment by mwrock** [comment]
I just made this change to the recipe. Thanks!
