### ISSUE TITLE
winrm timeout on build

### ISSUE THREAD

**Issue by andybrucenet** [mwrock/packer-templates#70]
Hi Matt - I just tried to build win2016 again with your latest changes and ran into a winrm timeout. So I used:

`PACKER_LOG=1 PACKER_LOG_PATH=~/vbox-2016.log packer build -force -only virtualbox-iso ./vbox-2016.json`

In the log file I saw:

`2017/01/04 23:59:36 packer: 2017/01/04 23:59:36 Executing VBoxManage: []string{"modifyvm", "packer-virtualbox-iso-1483592365", "--natpf1", "packercomm,tcp,127.0.0.1,3091,,55985"}`

Whoa. That isn't what we want!

It appears that when you set `winrm_port` in the json file, it should be the actual port on the *guest* not the host (the host port is dynamically calculated via the packercomm forwarding). Thus, there's really no need to allocate the `guest_winrm` port forwarding rule unless other scripts in the buildchain require it.

I modified the json file to use port 5985, restarted the build, and all is well. FWIW - you could also tell your users to use VBoxManage to discover the dynamic `packercomm` localhost port forward created by packer (in the above case, 3091) to connect via winrm directly (e.g. `pywinrm` and friends).

These packer tickets helped me:

- https://github.com/mitchellh/packer/issues/4310
- https://github.com/DanHam/packer/commit/686ec1866e3c8c0c1a19a310ca84209395c71c09

Specifically, in `vbox-2016.json`:

`"winrm_port": 5985,`

is the Fix.

I'm still waiting for win updates to complete so I can finish by testing creating a build box. Will let you know if I need to do any other patches.

Wrock on...

**Comment by mwrock** [comment]
What version of packer are you running? The recent PRs address issues found on packer 0.12.1 (latest today). If you are running an earlier version, then those changes might break you.

**Comment by andybrucenet** [comment]
Hi Matt -

```
CloudrasLLCsMBP:pentest-env l.abruce$ packer --version
0.12.0

```

After making the change the box did complete successfully, I have imported it into vagrant, and I'm running the final result right now.

The hang started only today; I don't have logs from previous builds (which - up through just a couple days ago - worked fine).

Go figure...

**Comment by mwrock** [comment]
closing for now. I have fixed a couple winrm bugs in the templates that arise with the latest packer versions.
