### ISSUE TITLE
Either set "ssh_skip_nat_mapping" or let Packer select a WinRM port dynamically

### ISSUE THREAD

**Issue by frischke** [mwrock/packer-templates#82]
In the current version of Packer (0.12.3), the virtualbox-iso builder tries to discover a suitable port for forwarding winrm (and ssh) traffic dynamically. Unfortunately Packer also overwrites an explicitly configured winrm_port with the discovered port, unless `ssh_skip_nat_mapping` is also set to `true` (default is `false`).

As a consequence, the vbox builds will eventually time out since Packer cannot connect to the Virtualbox VM successfully. I suggest to either add the `"ssh_skip_nat_mapping": "true"` option to the vbox-\<os\>.json config files or remove the explicitly configured winrm_port and the corresponding VBox port forwarding rule entirely and let Packer find a suitable port.

Relevant code references in Packer:
* [builder/virtualbox/common/step_forward_ssh.go, lines 30 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/builder/virtualbox/common/step_forward_ssh.go#L30): Unless `ssh_skip_nat_mapping` is `true`, it tries to discover a port and if found, configures port forwarding on the vbox vm. The discovered port is stored in the StateBag under the `"sshHostPort"` key.
* [builder/virtualbox/common/ssh.go, lines 16 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/builder/virtualbox/common/ssh.go#L16): Function that fetches port number from the StateBag.
* [builder/virtualbox/iso/builder.go, lines 246 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/builder/virtualbox/iso/builder.go#L246): References above function for determining the WinRMPort.
* [helper/communicator/step_connect_winrm.go, lines 100 ff.](https://github.com/mitchellh/packer/blob/v0.12.3/helper/communicator/step_connect_winrm.go#L100): Reads the winrm port from config, but then overwrites it with the return value of `WinRMPort`.

**Comment by frischke** [comment]
Unfortunately, the Packer documentation does not state that `ssh_skip_nat_mapping` also applies to the WinRM port (see the [current Packer doc](https://www.packer.io/docs/builders/virtualbox-iso.html#ssh_skip_nat_mapping)). I will probably open an issue in the Packer repository regarding this behavior too.

**Comment by mwrock** [comment]
closing this for now. I removed the winrm port setting alltogether and packer can now connect.
