### ISSUE TITLE
No Resource for "windows_feature_dism" for Windows 2016 Template

### ISSUE THREAD

**Issue by jagossel** [mwrock/packer-templates#84]
I'm not sure if I should post the issue here or on the Windows cookbook repository on Github.  For me, the Windows Server 2016 build fails with the following message: "`Cannot find a resource for windows_feature_dism on windows version 10.0.14393`".

I doubt that this will make a difference, but I do use a local copy of the Windows Server 2016 ISO file to keep from having to download and re-download the ISO file every time I do a build when running across errors.

If this issue needs to be reported on the Windows cookbook Github repository, please let me know and close this issue out.

And here is the log file of the build: [Windows2106BuildLog.txt](https://github.com/mwrock/packer-templates/files/921190/Windows2106BuildLog.txt)

**Comment by mwrock** [comment]
Yeah I am pretty sure this is windows cookbook issue. I ran the 2016 template about a month ago successfully. However, between that time and now, a new major version of chef has released along with major versions of the windows cookbook. It looks like the `windows_feature` is compliant with the new cookbook but there might be an incompatibility with server 2016.

**Comment by TaylorMonacelli** [comment]
My workaround is to remove "packer-templates::uninstall_powershell_ise" from vbox-2016.json
