### ISSUE TITLE
Question: What is the command type of command_shutdown

### ISSUE THREAD

**Issue by Stephanevg** [mwrock/packer-templates#89]
As described in the title, this is more a question then anything else. I am opening an issue, since I didn't get any answer on the IRC Channel. So trying here:

What type of shell is the shutdown_command ? 

It is not specified in the help located [here](https://www.packer.io/docs/builders/hyperv-iso.html#shutdown_command)

I would be expecting powershell, but my shutdown script (which is a simple "Stop-computer") doesn't work.

**Comment by Stephanevg** [comment]
changed title to be more accurate in question

**Comment by mwrock** [comment]
I'm pretty sure its the old style command shell - cmd.exe. The packer docs don't specify: https://www.packer.io/docs/builders/virtualbox-iso.html#shutdown_command
